# All available keys

# Escape, Enter, Tab, Backspace, Space, Insert, Delete, Home, End, PageUp, PageDown,
# ArrowLeft, ArrowUp, ArrowRight, ArrowDown,
# A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
# 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
# Num0, Num1, Num2, Num3, Num4, Num5, Num6, Num7, Num8, Num9, NumMultiply, NumAdd, NumSubtract, NumDivide, NumDecimal,
# F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F20,
# CapsLock

# All available modifiers

# Alt, LeftAlt, RightAlt,
# Control, LeftControl, RightControl,
# Shift, LeftShift, RightShift,
# Meta, LeftMeta, RightMeta, win, windows, cmd, command, super

# Change only values to the right of equal sign, any invalid entries will be ignored
[keybinds]
memory_slot_1 = 1
memory_slot_2 = 2
memory_slot_3 = 3
memory_slot_4 = 4
memory_slot_5 = 5
memory_slot_6 = 6
memory_slot_7 = 7
memory_slot_8 = 8
memory_slot_9 = 9
memory_slot_10 = 0

quick_slot_1 = F1
quick_slot_2 = F2
quick_slot_3 = F3
quick_slot_4 = F4
quick_slot_5 = F5
quick_slot_6 = F6
quick_slot_7 = F7
quick_slot_8 = F8
quick_slot_9 = F9
quick_slot_10 = F10

# Available if you have moon of nokstella equipped
memory_slot_11 = shift+1
memory_slot_12 = shift+alt+2

# Previous spell. Press once to go back one slot.
cycle_back = Num0

# Must match the in-game Attack or Guard key binding, depending which slot you equip catalyst.
# Available keys
# OFF, MouseRight, MouseLeft, A-Z, 0-9, Ctrl, Shift, Alt, Tab
auto_cast = MouseRight

# Must match the in-game Use Item key binding, the key you drink a flask with.
# Available keys
# OFF, A-Z, 0-9, Ctrl, Shift, Alt, Tab
auto_use = R
